### ISSUE TITLE
not deplying

### ISSUE THREAD

**Issue by ananth-28** [raveen2k3/FastlyWriteUB#5]
![image](https://user-images.githubusercontent.com/106482929/181496216-075dffe7-15ef-453f-822d-eac19dc85a57.png)

**Comment by raveen2k3** [comment]
@ananth-28 Fork it , and try again

**Comment by raveen2k3** [comment]
@raveen2k3 Change readme.md ,

Ps:- don't press host button directly , edit the link , 

else directly link heroku to ur git
